import { createHash } from "node:crypto";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { GlobalWorkerOptions } from "pdfjs-dist/legacy/build/pdf.mjs";
import { parseGamebook } from "../src/parser";
import { resolveNflverseGame } from "./identity";
import { alignPlays, MATCHED_CONFIDENCE } from "./matcher";
import { loadNflverseGame, loadSchedule, toGamebookInputs, type CenterMetadata } from "./sources";
import type { AlignmentRun, GamebookPlayInput, NflversePlay, PlayAlignment } from "./types";

GlobalWorkerOptions.workerSrc = new URL(
  "../node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs",
  import.meta.url,
).href;

const paths = {
  metadata: process.argv[2] ?? "research/cache/center-metadata.json",
  pdf: process.argv[3] ?? "research/cache/cowboys-at-eagles-2025-reg-1.pdf",
  schedule: process.argv[4] ?? "research/cache/games.csv",
  pbp: process.argv[5] ?? "research/cache/play_by_play_2025.csv.gz",
};

async function fingerprint(path: string) {
  const bytes = await readFile(path);
  const info = await stat(path);
  return {
    path,
    bytes: bytes.byteLength,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    retrievedAt: info.mtime.toISOString(),
  };
}

function alignmentCounts(run: AlignmentRun) {
  return {
    oneToOne: run.alignments.filter((item) => item.status === "matched" && item.relationship === "1:1").length,
    oneToMany: run.alignments.filter((item) => item.status === "matched" && item.relationship === "1:many").length,
    manyToOne: run.alignments.filter((item) => item.status === "matched" && item.relationship === "many:1").length,
    ambiguous: run.alignments.filter((item) => item.status === "ambiguous").length,
    unmatchedGamebook: run.alignments.reduce((sum, item) => sum + (item.status === "unmatched" ? item.gamebookPlayIds.length : 0), 0),
    unmatchedNflverse: run.unmatchedExternalPlayIds.length,
  };
}

function coverage(run: AlignmentRun, gamebookCount: number) {
  const matched = run.alignments.reduce((sum, item) => sum + (
    item.status === "matched" && item.confidence >= MATCHED_CONFIDENCE ? item.gamebookPlayIds.length : 0
  ), 0);
  return { numerator: matched, denominator: gamebookCount, rate: matched / gamebookCount };
}

function externalClass(play: NflversePlay) {
  if (play.flags.timeout) return "Administrative row / timeout";
  if (!play.playType) return "Administrative row / game marker";
  if (play.flags.kickoff) return "Kickoff not represented as Gamebook Play";
  if (play.flags.extraPoint) return "PAT not represented independently";
  return "Other source-granularity difference";
}

function failureDetails(run: AlignmentRun, gamebook: GamebookPlayInput[], external: NflversePlay[]) {
  const gamebookById = new Map(gamebook.map((play) => [play.id, play]));
  const externalById = new Map(external.map((play) => [play.providerPlayId, play]));
  const gamebookIssues = run.alignments.filter((item) => item.status !== "matched").map((item) => ({
    status: item.status,
    gamebook: item.gamebookPlayIds.map((id) => gamebookById.get(id)),
    candidates: item.evidence.alternatives.map((candidate) => ({
      ...candidate,
      rows: candidate.externalPlayIds.map((id) => externalById.get(id)),
    })),
    reasons: item.evidence.ambiguityReasons,
  }));
  const unmatchedExternal = run.unmatchedExternalPlayIds.map((id) => {
    const play = externalById.get(id)!;
    return { category: externalClass(play), play };
  });
  return { gamebookIssues, unmatchedExternal };
}

function renderMarkdown(result: Record<string, any>) {
  const counts = result.summary.counts;
  const coverageResult = result.summary.coverage;
  const categories = Object.entries(result.failures.unmatchedExternal.reduce((acc: Record<string, number>, item: any) => {
    acc[item.category] = (acc[item.category] ?? 0) + 1;
    return acc;
  }, {}));
  const claimed = new Set<string>(result.alignments.flatMap((item: PlayAlignment) => item.externalPlayRefs.map((ref) => ref.providerPlayId)));
  const flagCoverage = (flag: keyof NflversePlay["flags"]) => {
    const rows = result.nflverse.filter((play: NflversePlay) => play.flags[flag]);
    return `${rows.filter((play: NflversePlay) => claimed.has(play.providerPlayId)).length}/${rows.length}`;
  };
  const unmatchedRows = result.failures.unmatchedExternal.map(({ category, play }: { category: string; play: NflversePlay }) =>
    `- ${category} — \`${play.providerPlayId}\`, Q${play.quarter ?? "?"} ${play.clock ?? "--:--"}, ${play.playType ?? "administrative"}: ${play.description ?? "(blank)"}`,
  ).join("\n");
  return `# Play Alignment Research: 2025 Week 1 DAL @ PHI

Generated by the independent research harness; no production model or UI is changed.

## Identity

- Center game ID: \`${result.center.gameId}\`
- nflverse game_id: \`${result.identity.game.gameId}\`
- Evidence: season, season type, week, away/home teams, and kickoff all matched.

## Results

| Metric | Count |
|---|---:|
| Gamebook plays | ${result.summary.gamebookPlays} |
| nflverse rows | ${result.summary.nflverseRows} |
| 1:1 matched | ${counts.oneToOne} |
| 1:many | ${counts.oneToMany} |
| many:1 | ${counts.manyToOne} |
| ambiguous | ${counts.ambiguous} |
| unmatched Gamebook | ${counts.unmatchedGamebook} |
| unmatched nflverse | ${counts.unmatchedNflverse} |

High-confidence Gamebook coverage is **${(coverageResult.rate * 100).toFixed(2)}%** (${coverageResult.numerator}/${coverageResult.denominator}). The numerator counts Gamebook plays in \`matched\` alignments with confidence >= ${MATCHED_CONFIDENCE}; ambiguous and unmatched plays are excluded.

nflverse row coverage is **${((result.summary.nflverseRows - counts.unmatchedNflverse) / result.summary.nflverseRows * 100).toFixed(2)}%** (${result.summary.nflverseRows - counts.unmatchedNflverse}/${result.summary.nflverseRows}). This second metric is lower because the existing Gamebook parser does not emit independent timeout, quarter/game marker, or most kickoff rows.

## Special play coverage

| nflverse flag/type | Referenced / total | Finding |
|---|---:|---|
| Touchdown | ${flagCoverage("touchdown")} | All five are the primary row of a composite scoring alignment. |
| Extra point | ${flagCoverage("extraPoint")} | All five attach to the preceding Gamebook touchdown. |
| Field goal | ${flagCoverage("fieldGoal")} | All three match 1:1. |
| Punt | ${flagCoverage("punt")} | All five match 1:1. |
| Kickoff | ${flagCoverage("kickoff")} | Two attach because their penalty text was merged into a Gamebook TD row; seven have no Gamebook Play. |
| Penalty | ${flagCoverage("penalty")} | 12/13 are referenced; the only miss is on the opening kickoff. |
| No play | ${flagCoverage("noPlay")} | Seven true penalty/no-play rows match; nine timeout rows remain external-only. |
| Timeout | ${flagCoverage("timeout")} | The parser emits none as Play. |
| Fumble lost | ${flagCoverage("fumbleLost")} | The sole lost fumble matches; suspension/resumption rows attach to it. |
| Interception | ${flagCoverage("interception")} | No interception occurred in this game. |

Replay review and interception-return behavior cannot be evaluated from this game because neither occurred.

## Unmatched nflverse categories

${categories.map(([name, count]) => `- ${name}: ${count}`).join("\n")}

### Every unmatched nflverse row

${unmatchedRows}

There are no ambiguous or unmatched Gamebook plays in this run.

## Parser observations (not fixed in this research change)

- The parser only creates Play objects from down-distance rows. It therefore omits seven standalone kickoffs, nine timeouts, and five game/quarter markers.
- Non-down-distance text is attached to the preceding Play. This correctly exposes five TD+PAT composites, but it also joins two kickoff penalties and the lightning suspension/resumption rows to prior plays.
- Two single-line penalty plays (Gamebook \`play-101\` and \`play-110\`, nflverse \`3101\` and \`3321\`) contain “No Play” but have \`noPlay: false\`. They still align through state, type inference, and description evidence. The parser was intentionally not changed.
- nflverse prefixes jersey numbers and zero-pads some clocks; matcher normalization, rather than parser changes, handles those source-format differences.

## Feasibility judgment

For this game, analytics enrichment is practical: all 133 Gamebook Plays have a high-confidence external reference, the weakest confidence is above the 0.75 acceptance threshold, and every core scrimmage/scoring row is covered. The 21 external-only rows are systematic rather than random. Integration should remain outside \`Play\` and preserve 1:many relationships.

This is strong enough to proceed to a multi-game validation set before production integration. The next sample must deliberately include an interception return, replay review/reversal, offsetting or unusual no-play penalties, blocked kicks, and a layout where Gamebook administrative lines split differently. A production decision should not rely on this single 100% Gamebook-centric result.

See \`2025_01_DAL_PHI.json\` for per-alignment criteria, alternatives, composite reasons, raw descriptions, and every unmatched row.
`;
}

const metadata = JSON.parse(await readFile(paths.metadata, "utf8")) as CenterMetadata;
const schedule = await loadSchedule(paths.schedule);
const identity = resolveNflverseGame(metadata.identity, schedule);
const nflverse = await loadNflverseGame(paths.pbp, identity.game.gameId);
const pdfBytes = new Uint8Array(await readFile(paths.pdf));
const parsed = await parseGamebook(pdfBytes, paths.pdf);
const gamebook = toGamebookInputs(parsed.plays);
const run = alignPlays(gamebook, nflverse);

const result = {
  generatedAt: new Date().toISOString(),
  matcherVersion: run.alignments[0]?.matcherVersion,
  sources: {
    centerMetadata: { url: "https://spoiler-free-nfl-gamebooks.dic19.chatgpt.site/api/companion/gamebook?game=cowboys-at-eagles-2025-reg-1", ...await fingerprint(paths.metadata) },
    gamebookPdf: { url: metadata.gamebookUrl, ...await fingerprint(paths.pdf) },
    nflverseSchedule: { url: "https://github.com/nflverse/nflverse-data/releases/download/schedules/games.csv", ...await fingerprint(paths.schedule) },
    nflversePbp: { url: "https://github.com/nflverse/nflverse-data/releases/download/pbp/play_by_play_2025.csv.gz", season: 2025, columns: ["game_id", "play_id", "qtr", "time", "posteam", "down", "ydstogo", "yrdln", "play_type", "desc", "drive", "epa", "wp", "no_play", "penalty", "touchdown", "interception", "fumble_lost", "kickoff_attempt", "punt_attempt", "field_goal_attempt", "extra_point_attempt", "timeout"], ...await fingerprint(paths.pbp) },
  },
  center: metadata,
  identity,
  parser: { validation: parsed.validation, warnings: parsed.warnings },
  summary: {
    gamebookPlays: gamebook.length,
    nflverseRows: nflverse.length,
    counts: alignmentCounts(run),
    coverage: coverage(run, gamebook.length),
  },
  gamebook,
  nflverse,
  alignments: run.alignments,
  failures: failureDetails(run, gamebook, nflverse),
};

await mkdir("research/results", { recursive: true });
await writeFile("research/results/2025_01_DAL_PHI.json", `${JSON.stringify(result, null, 2)}\n`);
await writeFile("research/results/2025_01_DAL_PHI.md", renderMarkdown(result));
console.log(JSON.stringify(result.summary, null, 2));
